// Only these recipes are published. Uncomment a retained entry after its review.
// The generator uses this list for pages, previews, source and agent references.
export const PUBLISHED_RECIPES: readonly string[] = [
  // "app-cards/card-actions-grid",
  // "app-cards/card-icon-features",
  // "app-cards/card-with-badges",
  // "app-cards/card-with-stats",
  // "app-cards/card-with-switches",
  // "app-cards/stats-card-progress",
  // "app-cards/tasks-card",
  "cards/article-card",
  // "blog/article-card-footer",
  // "blog/article-cards-grid",
  // "blog/article-header",
  // "blog/byline",
  "banners/banner-background-image",
  // "blog/comment",
  // "blog/comment-html",
  // "blog/comment-thread",
  // "blog/tag-list",
  // "blog/vertical-article-card",
  // "buttons/button-with-menu",
  // "buttons/button-with-progress",
  // "buttons/copy-to-clipboard",
  // "buttons/social-buttons",
  // "buttons/split-button",
  "cards/gallery-card",
  "media/article-carousel",
  // "commerce/cart-line",
  // "commerce/mini-basket",
  // "commerce/order-summary",
  // "commerce/pricing-table",
  // "commerce/product-card",
  // "commerce/product-grid",
  // "data-display/contact-details",
  // "data-display/grouped-stats",
  // "data-display/stat-with-trend",
  // "data-display/stats-grid",
  // "data-display/stats-with-controls",
  // "data-display/stats-with-diff",
  // "data-display/stats-with-segments",
  // "data-display/summary-list",
  // "data-display/table-reviews",
  // "data-display/table-sortable",
  // "data-display/table-sticky-header",
  // "data-display/table-with-selection",
  // "data-display/task-list",
  // "errors/error-404",
  // "errors/error-404-image",
  // "errors/error-500",
  // "errors/error-503",
  // "faq/faq-page-header",
  // "faq/faq-simple",
  "content/faq",
  // "faq/faq-with-image",
  // "forms/address-fields",
  // "forms/autocomplete-async",
  // "forms/choice-cards-checkbox",
  // "forms/choice-cards-radio",
  // "forms/contact-form",
  // "forms/dropzone",
  // "forms/floating-label",
  // "forms/forgot-password",
  // "forms/forgot-password-on-label",
  // "forms/inline-search-form",
  // "forms/input-validation",
  // "forms/input-with-button",
  // "forms/input-with-tooltip",
  // "forms/language-picker",
  // "forms/number-with-currency",
  // "forms/password-strength",
  // "forms/settings-rows",
  // "forms/sign-in",
  "forms/sign-in-with-errors",
  // "forms/sign-up",
  "grids/grid-asymmetric",
  // "grids/grid-leading-item",
  "grids/grid-subgrid",
  // "navigation/footer-centered",
  // "navigation/footer-simple",
  // "navigation/footer-with-columns",
  // "navigation/footer-with-social",
  // "navigation/header-mega-menu",
  // "navigation/header-simple",
  // "navigation/header-with-menus",
  // "navigation/header-with-search",
  // "navigation/header-with-tabs",
  // "navigation/mobile-nav",
  // "navigation/page-header",
  // "navigation/side-nav",
  // "navigation/side-nav-rail",
  // "navigation/side-nav-two-sections",
  // "navigation/side-nav-with-groups",
  // "navigation/side-nav-with-search",
  // "navigation/side-nav-with-segmented-control",
  // "navigation/social-links",
  // "navigation/table-of-contents",
  // "page-sections/banner",
  // "page-sections/banner-warning",
  "banners/banner-with-image",
  // "page-sections/call-to-action",
  // "page-sections/call-to-action-with-media",
  "forms/contact-us-with-details",
  // "page-sections/cookie-banner",
  // "page-sections/email-banner",
  // "page-sections/embed-map",
  // "page-sections/embed-video",
  // "page-sections/empty-state",
  // "page-sections/feature-grid",
  // "page-sections/features-with-cards",
  // "page-sections/features-with-title",
  // "page-sections/gallery-lightbox",
  "heroes/hero-background-image",
  // "page-sections/hero-centered",
  // "page-sections/hero-content-left",
  // "page-sections/hero-with-bullets",
  "heroes/hero-with-image",
  "media/image-comparison",
  // "page-sections/logo-wall",
  // "page-sections/person-grid",
  // "page-sections/section-header",
  // "page-sections/stepper-progress",
  // "page-sections/testimonial",
  // "page-sections/testimonial-carousel",
  "content/timeline",
  // "sliders/number-input-with-slider",
  // "sliders/slider-with-marks",
  // "sliders/slider-with-output",
  // "users/user-button",
  "cards/profile-card",
  // "users/user-info-with-icons",
  // "users/user-menu",
  // "users/users-grid",
  // "users/users-table",
  // "users/users-table-with-roles",
];
