/**
 * The recipes registry, generated from the folders under src/recipes.
 *
 * Every recipe is a folder, src/recipes/<category>/<slug>/, holding
 * Recipe.tsx, recipe.css, meta.ts and recipe.test.tsx. This script
 * scans them and writes the registry modules:
 *
 *   src/recipes/generated/meta.ts   — one entry per recipe: slug,
 *                                      category and meta. JSX-free, so the
 *                                      navigation and the markdown export
 *                                      can list recipes without loading
 *                                      a single component or stylesheet.
 *   src/recipes/generated/index.ts        — the same entries with the Recipe
 *                                      component, for the pages to render.
 *   src/recipes/generated/previews.ts — lazy components for the gallery,
 *                                      backed by one generated module per
 *                                      category, loaded near the viewport.
 *   src/recipes/generated/source.ts — the raw text of Recipe.tsx and
 *                                      recipe.css per slug, read from
 *                                      disk, so the code a page shows is
 *                                      the code its preview runs. Kept
 *                                      apart so the index, which renders
 *                                      every preview, ships no source.
 *
 * Runs before dev and build (see package.json); `pnpm check:recipes`
 * checks the folders themselves.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PUBLISHED_RECIPES } from "../src/recipes/recipes.js";
import { RECIPE_CATEGORIES } from "../src/recipes/categories.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(ROOT, "src", "recipes");
const REQUIRED = ["Recipe.tsx", "recipe.css", "meta.ts", "recipe.test.tsx"];

interface Found {
  category: string;
  slug: string;
  order: number;
}

const listed = new Set(RECIPE_CATEGORIES.map((c) => c.slug));
const found: Found[] = [];
const published = new Set(PUBLISHED_RECIPES);
const discovered = new Set<string>();
const problems: string[] = [];

for (const category of readdirSync(DIR)) {
  const categoryDir = join(DIR, category);
  if (!statSync(categoryDir).isDirectory()) continue;
  // This script's own output lives here; it is not a category.
  if (category === "generated") continue;
  if (!listed.has(category)) {
    problems.push(`src/recipes/${category}/ is not listed in src/recipes/categories.ts`);
    continue;
  }
  for (const slug of readdirSync(categoryDir)) {
    const dir = join(categoryDir, slug);
    if (!statSync(dir).isDirectory()) continue;
    const missing = REQUIRED.filter((f) => !existsSync(join(dir, f)));
    if (missing.length) {
      problems.push(`src/recipes/${category}/${slug}/ is missing ${missing.join(", ")}`);
      continue;
    }
    // The display order is meta.order (lower first), then the slug. Read
    // as text: meta.ts is JSX-free but importing it here would pull the
    // type module through tsx for every recipe on every dev start.
    const meta = readFileSync(join(dir, "meta.ts"), "utf8");
    const order = Number(meta.match(/\border:\s*(\d+)/)?.[1] ?? 1000);
    const key = `${category}/${slug}`;
    discovered.add(key);
    if (published.has(key)) found.push({ category, slug, order });
  }
}

for (const c of RECIPE_CATEGORIES) {
  if (!existsSync(join(DIR, c.slug)))
    problems.push(`categories.ts lists "${c.slug}" but src/recipes/${c.slug}/ does not exist`);
}

for (const key of published) {
  if (!discovered.has(key))
    problems.push(`Published recipe "${key}" has no complete source folder`);
}
if (published.size !== PUBLISHED_RECIPES.length) problems.push("Duplicate published recipe");

if (problems.length) {
  console.error(`build-recipes: ${problems.length} problem(s)\n- ${problems.join("\n- ")}`);
  process.exit(1);
}

const categoryIndex = new Map(RECIPE_CATEGORIES.map((c, i) => [c.slug, i]));
found.sort(
  (a, b) =>
    categoryIndex.get(a.category)! - categoryIndex.get(b.category)! ||
    a.order - b.order ||
    a.slug.localeCompare(b.slug),
);

const HEADER = [
  "// Generated by scripts/build-recipes.mts from the folders under src/recipes.",
  "// Do not edit: add or change an recipe folder and rerun `pnpm dev` or `pnpm build`.",
  "",
];

const metaModule = [
  ...HEADER,
  'import type { RecipeMetaEntry } from "../types";',
  ...found.map(
    ({ category, slug }, i) => `import { meta as meta${i} } from "../${category}/${slug}/meta";`,
  ),
  "",
  "/** Every recipe's identity and meta, in category order then display order. JSX-free. */",
  "export const RECIPE_META: RecipeMetaEntry[] = [",
  ...found.map(
    ({ category, slug }, i) =>
      `  { slug: ${JSON.stringify(slug)}, category: ${JSON.stringify(category)}, meta: meta${i} },`,
  ),
  "];",
  "",
];

const registry = [
  ...HEADER,
  'import type { RecipeEntry } from "../types";',
  'import { RECIPE_META } from "./meta";',
  ...found.map(
    ({ category, slug }, i) => `import Recipe${i} from "../${category}/${slug}/Recipe";`,
  ),
  "",
  "/** Every recipe with its component, in the same order as RECIPE_META. */",
  "export const RECIPES: RecipeEntry[] = [",
  ...found.map((_, i) => `  { ...RECIPE_META[${i}]!, Recipe: Recipe${i} },`),
  "];",
  "",
];

const source = [
  ...HEADER,
  'import type { RecipeSource } from "../types";',
  "",
  "/** The raw source of each recipe, by slug: exactly the files the preview renders. */",
  "export const RECIPE_SOURCE: Record<string, RecipeSource> = {",
  ...found.flatMap(({ category, slug }) => {
    const dir = join(DIR, category, slug);
    const tsx = readFileSync(join(dir, "Recipe.tsx"), "utf8");
    const css = readFileSync(join(dir, "recipe.css"), "utf8");
    return [
      `  ${JSON.stringify(slug)}: {`,
      `    tsx: ${JSON.stringify(tsx)},`,
      `    css: ${JSON.stringify(css)},`,
      "  },",
    ];
  }),
  "};",
  "",
];

const previews = [
  ...HEADER,
  'import { lazy, type ComponentType, type LazyExoticComponent } from "react";',
  "",
  "/** Lazy identities stay stable; recipes in a category share an import boundary. */",
  "export const RECIPE_PREVIEWS: Record<string, LazyExoticComponent<ComponentType>> = {",
  ...found.map(
    ({ category, slug }, i) =>
      `  ${JSON.stringify(slug)}: lazy(() => import("./preview-${category}").then((m) => ({ default: m.Recipe${i} }))),`,
  ),
  "};",
  "",
];

const files: Record<string, string[]> = {
  "generated/meta.ts": metaModule,
  "generated/index.ts": registry,
  "generated/source.ts": source,
  "generated/previews.ts": previews,
};
for (const { slug: category } of RECIPE_CATEGORIES) {
  files[`generated/preview-${category}.ts`] = [
    ...HEADER,
    ...found.flatMap((entry, i) =>
      entry.category === category
        ? [`export { default as Recipe${i} } from "../${category}/${entry.slug}/Recipe";`]
        : [],
    ),
    "",
  ];
}
mkdirSync(join(DIR, "generated"), { recursive: true });
for (const [name, lines] of Object.entries(files)) writeFileSync(join(DIR, name), lines.join("\n"));
// The repo's format gate covers generated files too.
execFileSync("npx", ["oxfmt", ...Object.keys(files).map((name) => join(DIR, name))], {
  stdio: "ignore",
});
console.log(
  `build-recipes: ${found.length} recipe(s) in ${listed.size} categories → src/recipes/${Object.keys(files).join(", ")}`,
);
