// Drift gate for the published `loamui` agent skill (skills/loamui).
//
// A skill that lies is worse than no skill, so CI verifies:
//   1. references/ matches the docs source (regenerated by the docs export;
//      a stale committed copy fails);
//   2. every component the SKILL.md table names exists in the library;
//   3. every local link in SKILL.md resolves;
//   4. SKILL.md stays inside its context budget (it is read in full on every
//      LoamUI task — depth belongs in references/).
// Pass --urls to also check that each https://loamui.com link returns 200.
import { execSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILL_DIR = join(ROOT, "skills", "loamui");
const SKILL = join(SKILL_DIR, "SKILL.md");
const COMPONENTS_DIR = join(ROOT, "packages", "core", "src", "components");
const BUDGET_CHARS = 16_000; // ≈ 4k tokens

const failures = [];
const fail = (msg) => failures.push(msg);

// 1. references in sync -----------------------------------------------------
function referenceSnapshot(dir, prefix = "") {
  const files = new Map();
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const key = prefix + entry.name;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      for (const [nested, content] of referenceSnapshot(path, `${key}/`))
        files.set(nested, content);
    } else files.set(key, readFileSync(path, "utf8"));
  }
  return files;
}
const before = referenceSnapshot(join(SKILL_DIR, "references"));
execSync("npx tsx --tsconfig scripts/tsconfig.export.json scripts/export-markdown.mts", {
  cwd: join(ROOT, "apps", "docs"),
  stdio: "pipe",
});
const after = referenceSnapshot(join(SKILL_DIR, "references"));
const drift = [...new Set([...before.keys(), ...after.keys()])].filter(
  (file) => before.get(file) !== after.get(file),
);
if (drift.length)
  fail(`references/ was stale — review the regenerated files:\n${drift.join("\n")}`);

// 2. the frontmatter parses ------------------------------------------------
// The skills installer reads it to find the skill at all: a stray ": " in an
// unquoted description made the skill vanish from the installer's listing.
const md = readFileSync(SKILL, "utf8");
{
  const match = /^---\n([\s\S]*?)\n---\n/.exec(md);
  if (!match) fail("SKILL.md has no frontmatter block");
  else {
    try {
      const front = yaml.load(match[1]);
      for (const key of ["name", "description"])
        if (typeof front?.[key] !== "string" || !front[key].trim())
          fail(`SKILL.md frontmatter has no ${key}`);
      if (front?.name !== "loamui")
        fail(`SKILL.md frontmatter name is "${front?.name}", not "loamui"`);
    } catch (error) {
      fail(`SKILL.md frontmatter is not valid YAML: ${error.message.split("\n")[0]}`);
    }
  }
}

// 3. named components exist ----------------------------------------------
const existing = new Set(readdirSync(COMPONENTS_DIR));
const table = md.split("## Components")[1]?.split("\n## ")[0] ?? "";
for (const row of table
  .split("\n")
  .filter((l) => l.startsWith("| ") && !l.startsWith("| Category") && !l.startsWith("| ---"))) {
  const names =
    row
      .split("|")[2]
      ?.split(",")
      .map((s) => s.trim())
      .filter(Boolean) ?? [];
  for (const name of names)
    if (!existing.has(name))
      fail(`SKILL.md names "${name}" but packages/core/src/components/${name} does not exist`);
}

// 4. local links resolve ----------------------------------------------------
for (const m of md.matchAll(/\]\(((?:references|assets)\/[^)#]+)\)/g)) {
  if (!existsSync(join(SKILL_DIR, m[1]))) fail(`SKILL.md links to missing file ${m[1]}`);
}
for (const m of md.matchAll(/`((?:references|assets)\/[a-z/.-]+\.(?:md|mjs))`/g)) {
  if (!existsSync(join(SKILL_DIR, m[1]))) fail(`SKILL.md mentions missing file ${m[1]}`);
}

// 5. budget -----------------------------------------------------------------
if (md.length > BUDGET_CHARS)
  fail(
    `SKILL.md is ${md.length} chars; budget is ${BUDGET_CHARS} (≈4k tokens). Move depth into references/.`,
  );

// optional: live URLs -------------------------------------------------------
if (process.argv.includes("--urls")) {
  const urls = [...new Set([...md.matchAll(/https:\/\/loamui\.com[^\s)>`]*/g)].map((m) => m[0]))];
  for (const url of urls) {
    const res = await fetch(url, { method: "HEAD" }).catch(() => null);
    if (!res || res.status !== 200) fail(`${url} → ${res ? res.status : "unreachable"}`);
  }
}

if (failures.length) {
  console.error(`check-skill: ${failures.length} problem(s)\n- ` + failures.join("\n- "));
  process.exit(1);
}
console.log(
  `check-skill: OK (${md.length} chars, ${existing.size} components, references in sync)`,
);
